### ISSUE TITLE
Unknown reference to Response type in main.d.ts

### ISSUE THREAD

**Issue by fercmartinez** [microsoft/vscode-oniguruma#7]
Hello! 
First of all, thanks for this great tool 😄 

I wanted to bring up that there are two references to a `Response` type in `main.d.ts` file that appear as problems in VSCode when I install de extension. Having said that, it's not causing any compilation issues, but it becomes a bit annoying having to dismiss the problem every time it comes up.

Below are the `Response` references:

https://github.com/microsoft/vscode-oniguruma/blob/d0c4721b1c8bbee8a63bc9b2e0b6b0f9d3a9b698/main.d.ts#L6

https://github.com/microsoft/vscode-oniguruma/blob/d0c4721b1c8bbee8a63bc9b2e0b6b0f9d3a9b698/main.d.ts#L11

As a "quick patch", I just edited my local version of `main.d.ts` and just deleted the `Response` types from the two places I stated above.

Could you please take a look? 

Thanks in advance for your help!

**Comment by alexdima** [comment]
* `vscode-oniguruma` can also run in web browsers
* in web browsers, there is a special API where a WASM script can be instantiated from a streaming HTTP request. The idea is that the browser begins parsing/instantiating the WASM script before the .wasm request itself has finished. This is available via [`WebAssembly.instantiateStreaming`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming)
* so that is why `vscode-oniguruma` accepts as argument a [`Response`](https://github.com/microsoft/TypeScript/blob/514d8d88416f9112acd94be07e95d62b8d957169/lib/lib.dom.d.ts#L12716), which is the return type from calling browser's `fetch` API.

**Comment by fercmartinez** [comment]
Hi Alexandru!
Thanks for your previous response. I wanted to come back and give some closure to this issue, since I found what my problem was. 

First of all, I'll start by saying that although I said I had no compilation issue, I was wrong: and I was not able to compile my project.

Now the problem was that the `Response` type, as you mentioned, is present in the browser, and I was not including the `"DOM"` library in my `tsconfig.json` file. 

Just adding that missing library to the `lib` array in `tsconfig.json` fixed my compliation issue.

Thanks again for your response.
Cheers!
